chore: add docker info in readme & release, update docker task to include partial versions
kidle-dev/kidle pull request #24
Opened 2021-10-09 05:53 UTC by Animeshz

Remaining task of #10 (let me know if any changes are needed).

2021-10-12 06:54 UTC, orphaner requested changes

2021-10-12 06:54 UTC, orphaner commented on hack/push-docker-image.sh
> +for EXP_TAG in ${TAGS[@]}; do
OK, this is great to iterate here

2021-10-12 06:54 UTC, orphaner commented on hack/push-docker-image.sh
> +echo ${TAG} | IFS="." read major minor revision
this breaks the usage of this script in the snapshot workflow. 
I'm wondering if there is a way to call this script like: `TAGS="1.0.0 1.0 1" push-docker-image.sh` and exclude the logic of calculating the tags from here to the release workflow. Is there a github action to calculate the tags?

2021-10-12 09:07 UTC, Animeshz commented on hack/push-docker-image.sh
> +echo ${TAG} | IFS="." read major minor revision
@orphaner Yes, you could not change `IFS`, which defaults to space character ` `. But where would you send this information from (like in workflow)?

I'm also not sure how snapshot would look like, if snapshot is to look something like vx.y.z-rc1 or -alpha1 etc then it'll be better not to override the `x.y.z`, `x.y` and `x.` versions, they should be overridden in stable release isn't it? Maybe just check if -rc{x} exist in the snapshot and if it does do nothing, or else do as it is doing?

2021-10-19 07:55 UTC, orphaner commented
hello @Animeshz , sorry for the delay on that. I had a hard past week at work and this week-end I've played building lego with my little boy :)

regarding this pull request, let me clarify. In the `release.yml` workflow there is a missing step to build the operator docker image. 
In this new step we could imagine using [this action](https://github.com/jupyterhub/action-major-minor-tag-calculator) to get the desired tag list.
The `push-docker-image.sh` should still take the `TAG` env var ; that may be a list separated by a ,

I've created a slack channel so that we could discuss more easily: https://kidle-dev.slack.com/archives/C02JXP2JTK2

2021-10-25 08:16 UTC, orphaner requested changes
Hello; we are almost good for this PR, congrats :tada:

2021-10-25 08:16 UTC, orphaner commented on .github/workflows/release.yml
> +          TAG=${{env.GITHUB_REF_SLUG}} TAGS=${{ join(fromJson(steps.dockertags.outputs.tags)) }} make WHAT=operator build-multi-arch-image
`TAG` is not necessary anymore ; `TAGS` can handle a single value

2021-10-25 08:16 UTC, orphaner commented on .github/workflows/snapshot.yaml
> +        TAG=${{env.GITHUB_REF_SLUG}} TAGS=${{ join(fromJson(steps.dockertags.outputs.tags)) }} make WHAT=operator build-multi-arch-image
`TAGS=${{env.GITHUB_REF_SLUG}} make WHAT=operator build-multi-arch-image`
should be OK

2021-10-25 08:16 UTC, orphaner commented on hack/push-docker-image.sh
> +for EXP_TAG in ${TAGS}; do
now there is just an iteration over `TAGS` ; 
`EXP_TAG` has to renamed to `TAG`

2021-10-25 08:16 UTC, orphaner commented on hack/push-docker-image.sh
> +  docker manifest create -a "${IMAGE}:${EXP_TAG}" \
`EXP_TAG` => `TAG`

2021-10-25 08:16 UTC, orphaner commented on hack/push-docker-image.sh
> +    docker manifest annotate --arch "$arch" "${IMAGE}:${EXP_TAG}" "${IMAGE}:${TAG}-$arch"
`EXP_TAG` => `TAG`

2021-10-25 08:16 UTC, orphaner commented on hack/push-docker-image.sh
> +  docker manifest push "${IMAGE}:${EXP_TAG}"
`EXP_TAG` => `TAG`

2021-10-25 08:19 UTC, Animeshz commented on .github/workflows/release.yml
> +          TAG=${{env.GITHUB_REF_SLUG}} TAGS=${{ join(fromJson(steps.dockertags.outputs.tags)) }} make WHAT=operator build-multi-arch-image
@orphaner TAG is used by line number 22:

```bash
make WHAT=$WHAT docker GOARCH="$arch"
```

2021-10-25 08:23 UTC, Animeshz commented on .github/workflows/release.yml
> +          TAG=${{env.GITHUB_REF_SLUG}} TAGS=${{ join(fromJson(steps.dockertags.outputs.tags)) }} make WHAT=operator build-multi-arch-image
Its build once, tag many.

2021-10-25 10:31 UTC, orphaner commented on .github/workflows/release.yml
> +          TAG=${{env.GITHUB_REF_SLUG}} TAGS=${{ join(fromJson(steps.dockertags.outputs.tags)) }} make WHAT=operator build-multi-arch-image
ho yes, my bad

2021-10-25 10:38 UTC, merged

2021-10-25 10:39 UTC, orphaner commented
@Animeshz I've just accepted your PR; thanks again for your help :+1: