Add create command to kidlectl (#21)
kidle-dev/kidle pull request #25
Opened 2021-10-19 19:01 UTC by doniacld

### Description
Add create idling resource command to kidlectl to close #21.

### Test

I had to comment the installation of kustomize to make the installation works.
I could test manually:

* Creation of a resource without passing the idle flag
```
[donia@localhost kidlectl]$ ./bin/kidlectl create kidle-test --kubeconfig=~/.kubeconfig -n default -r deployments/kidle
2021-10-26T20:57:03.186+0200	INFO	creating the idling resource	{"namespace": "default", "name": "kidle-test", "ref": "deployments/kidle"}
2021-10-26T20:57:03.204+0200	INFO	idling resource created	{"namespace": "default", "name": "kidle-test", "ref": "deployments/kidle"}
``` 

```
[donia@localhost ~]$ kubectl get idlingresources
NAME         IDLE    REFKIND       REFNAME
kidle-test   false   deployments   kidle
```
* Creation of a resource with the idle flag
```
[donia@localhost kidlectl]$ ./bin/kidlectl create kidle-test --kubeconfig=~/.kubeconfig -n default -r deployments/kidle -i true
2021-10-26T21:04:47.087+0200	INFO	creating the idling resource	{"namespace": "default", "name": "kidle-test", "ref": "deployments/kidle"}
2021-10-26T21:04:47.105+0200	INFO	idling resource created	{"namespace": "default", "name": "kidle-test", "ref": "deployments/kidle"}
``` 

```
[donia@localhost ~]$ kubectl get idlingresources
NAME         IDLE    REFKIND       REFNAME
kidle-test   true    deployments   kidle
```

* Attempt of creation with an unknown kind
```
[donia@localhost kidlectl]$ ./bin/kidlectl create kidle-test --kubeconfig=~/.kubeconfig -n default -r foo/kidle -i true
2021-10-28T19:33:19.388+0200	INFO	creating the idling resource	{"namespace": "default", "name": "kidle-test", "ref": "foo/kidle"}
2021-10-28T19:33:19.472+0200	ERROR	unable to create an idling resource	{"error": "invalid resource kind; got `foo` expected one of: cj, cronjob, cronjobs, deploy, deployment, deployments, statefulset, statefulsets, sts"}
``` 

### TODO

- [x] Add the validation kind resource call
- [x] Add the `kidlectl create` command to the manifest in the userguide

2021-10-19 19:03 UTC, doniacld commented on cmd/kidlectl/pkg/kidleclient.go
> +	logf.Log.Info("Idling resource", "ir", ir)
remove this line

2021-10-25 10:40 UTC, orphaner commented
hello @doniacld; how can we get organized so that we can work together finishing this PR?

2021-10-26 19:21 UTC, doniacld commented
> hello @doniacld; how can we get organized so that we can work together finishing this PR?

Hey @orphaner!
Sorry for the delay, I pinged you on Slack yesterday.
I have been able to test the written code 🍾 
Everything seems to work, I added the code from the discovery in the refactoring.

I just have one problem from Sonar, it points a duplication between [idle.go](https://github.com/kidle-dev/kidle/blob/d206ccbfa51f5ee2698432548547fa306be58a84/cmd/kidlectl/idle.go) and [wakeup.go](https://github.com/kidle-dev/kidle/blob/d206ccbfa51f5ee2698432548547fa306be58a84/cmd/kidlectl/wakeup.go) even if the logs are different.
If you have any hint about it, I'll take it to pass the CI. 
I would be happy yo have your review and discuss the code.

2021-10-28 08:48 UTC, orphaner requested changes

2021-10-28 08:48 UTC, orphaner commented on cmd/kidlectl/pkg/kidleclient.go
> +	// TODO validate if the kind is known
please have a look at this commit: https://github.com/kidle-dev/kidle/commit/81c280bc325182f9f7cfe9674d916723275b1444

2021-10-28 08:48 UTC, orphaner commented on cmd/kidlectl/main.go
> +	DiscoveryCmd discoveryCommandOptions `command:"discovery" description:"discover allowed Group Version Kind"`
to remove ; on my branch it was part of the proof of concept; there is no need to keep it here

2021-10-28 08:48 UTC, orphaner commented on cmd/kidlectl/main.go
> +	case "discovery":
to remove

2021-10-28 17:35 UTC, doniacld commented on cmd/kidlectl/main.go
> +	case "discovery":
Fixed.

2021-10-28 17:36 UTC, doniacld commented on cmd/kidlectl/main.go
> +	DiscoveryCmd discoveryCommandOptions `command:"discovery" description:"discover allowed Group Version Kind"`
Fixed, I removed the discovery command.

2021-10-29 10:21 UTC, merged

2021-10-29 10:22 UTC, orphaner commented
LGTM ; it's now merged :tada: